server:
  port: 8080

spring:
  application:
    name: contur-focus-client
  datasource:
    url: jdbc:postgresql://127.0.0.1/batch
    username: postgres
    password: Zxcvb`123

  batch:
      jdbc:
        initializer-enabled: true
        initialize-schema: "always"
      job:
        enabled: true

#  datasource:
#    url: jdbc:oracle:thin:@prd-oracle-dwh-act.corp.sbibankllc.ru:1521/xe
#    username: EXTDATAAPP
#    password: hsC7dBIE:tskrFcQ
#    driver-class-name: oracle.jdbc.OracleDriver

kontur:
  url: https://focus-api.kontur.ru/
  key: 3208d29d15c507395db770d0e65f3711e40374df
  methods:
    req: req                                           # (Базовые реквизиты)
    petitionersOfArbitration: petitionersOfArbitration # (Статистика по истцам в арбитраже)
    excerpt: excerpt                                   # (Выписка из ЕГРЮЛ/ЕГРИП)
    finan: finan                                       # (Финансовый анализ)
    govPurchasesOfCustomer: govPurchasesOfCustomer     # (Госзакупки заказчика)



